# Generated by Django 4.2.27 on 2026-01-18 13:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('watchlist_app', '0002_streamplateform_watchlist_delete_move'),
    ]

    operations = [
        migrations.RenameField(
            model_name='watchlist',
            old_name='titel',
            new_name='title',
        ),
    ]
