# Generated by Django 4.2.27 on 2026-01-18 18:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('watchlist_app', '0003_rename_titel_watchlist_title'),
    ]

    operations = [
        migrations.AddField(
            model_name='watchlist',
            name='platform',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, related_name='whatchlist', to='watchlist_app.streamplateform'),
            preserve_default=False,
        ),
    ]
